### ISSUE TITLE
Business Central image repo name changed

### ISSUE THREAD

**Issue by staedter** [lippertmarkus/helm-charts#3]
I just tried running the BC helm charts in Azure and the pod could not pull the Business Central image
![image](https://user-images.githubusercontent.com/46670623/111055890-8f4d0c80-847a-11eb-834c-6ffee60a40b6.png)

I think it is because the old repo where MSFT hosted the images was deleted and replaced with mcr.microsoft.com/businesscentral

BTW amazing project. I was blown away... especially with the vagrant support ❤

I created a draft PR but it failed.

**Comment by lippertmarkus** [comment]
Thanks for the feedback, great that it helps you! I reviewed the PR.

**Comment by lippertmarkus** [comment]
New chart version 1.0.3 is now released using the new repo and right tag. Thank you.
