### ISSUE TITLE
Replicas >0

### ISSUE THREAD

**Issue by erbg** [lippertmarkus/helm-charts#9]
Hello,

I was trying to understand if BC supports more than 1 replica (POD) connected to an external Database.
Do you have some information about that?

Best regards

**Comment by lippertmarkus** [comment]
Hello, 
yes it's possible, but there are limitations: 
1. Multiple BC service tiers are not able to share session data between each other, so you need to enable sticky sessions (same person is always directed to the same pod) in your ingress controller. 
2. With sticky sessions enabled, if one of the pod fails, the users sticking to the failing  instance can't transparently continue working on another one. If their "assigned" instance fails they would be redirected to the login prompt and need to log in again.

**Comment by erbg** [comment]
Wow, great.
Sticky sessions are already in place.

My i ask a second thing, what about Job Queue, how do you handle this?

**Comment by lippertmarkus** [comment]
What do you mean? Jobs are stored in the external database and are executed by any service tier that has the Job Queue enabled.

**Comment by erbg** [comment]
My question is always connected to a multi pod environment. If i have 2 PODs that have a Job Queue enabled. Is BC then executing a timer job just once on one POD or will it execute twice? Just to understand if i need a special deployment for the pods with Job Queue enabled.
Thanks.

**Comment by lippertmarkus** [comment]
BC will execute it just once

**Comment by erbg** [comment]
Great! Thanks
